apiVersion: v1
kind: Namespace
metadata:
  name: beetroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beetroot-deployment
  name: beetroot-deployment
  namespace: beetroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beetroot-deployment
  template:
    metadata:
      labels:
        app: beetroot-deployment
    spec:
      containers:
      - image: helgeste/beetroot:latest
        name: beetroot
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: beetroot-np-svc
  name: beetroot-np-svc
  namespace: beetroot
spec:
  ports:
  - name: beetroot-service
    nodePort: 30123
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: beetroot-deployment  
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rev-proxy-configmap
  namespace: beetroot
data: 
  default.conf: | 
      server {
      listen 80;

      location / {
              proxy_pass http://10.103.233.56:8080/;
      }
      location /news {
              proxy_pass http://10.103.233.56:8080/api/v1/news;
      }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rev-proxy-deploy
  name: rev-proxy-deploy
  namespace: beetroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rev-proxy-deploy
  template:
    metadata:
      labels:
        app: rev-proxy-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80